"""Tune weighted RRF fusion for cached BM25 + dense rankings.

This script uses candidate rankings previously generated by
save_hybrid_candidates.py.

It does NOT run BM25 or Qwen again.

It tests different dense-retrieval weights and evaluates each
configuration using the MusicCRS evaluation utilities.
"""

import argparse
import json

from .evaluation.evaluate import evaluate


# ---------------------------------------------------------
# Dense weights to test
# ---------------------------------------------------------

DENSE_WEIGHTS = [
    0.00,
    0.05,
    0.10,
    0.15,
    0.20,
    0.25,
    0.30,
    0.40,
    0.50,
]


def weighted_rrf(
    bm25_tracks: list[str],
    dense_tracks: list[str],
    topk: int,
    dense_weight: float,
    rrf_k: int = 60,
) -> list[str]:
    """Combine BM25 and dense rankings using weighted RRF.

    BM25 is treated as the primary retrieval signal.

    Dense retrieval is used as a secondary semantic signal.

    Args:
        bm25_tracks:
            Ranked BM25 track IDs.

        dense_tracks:
            Ranked dense retrieval track IDs.

        topk:
            Number of final tracks to return.

        dense_weight:
            Weight assigned to the dense ranking.

        rrf_k:
            Reciprocal Rank Fusion constant.

    Returns:
        Fused ranked list of track IDs.
    """

    scores: dict[str, float] = {}

    # -----------------------------------------------------
    # BM25 contribution
    #
    # BM25 weight = 1.0
    # -----------------------------------------------------

    for rank, track_id in enumerate(
        bm25_tracks,
        start=1,
    ):
        score = 1.0 / (rrf_k + rank)

        scores[track_id] = (
            scores.get(track_id, 0.0)
            + score
        )

    # -----------------------------------------------------
    # Dense contribution
    # -----------------------------------------------------

    for rank, track_id in enumerate(
        dense_tracks,
        start=1,
    ):
        score = (
            dense_weight
            / (rrf_k + rank)
        )

        scores[track_id] = (
            scores.get(track_id, 0.0)
            + score
        )

    # -----------------------------------------------------
    # Sort tracks by fused score
    # -----------------------------------------------------

    ranked_tracks = sorted(
        scores.items(),
        key=lambda item: item[1],
        reverse=True,
    )

    return [
        track_id
        for track_id, _ in ranked_tracks[:topk]
    ]


def build_predictions(
    candidates: list[dict],
    dense_weight: float,
    topk: int,
    rrf_k: int,
) -> list[dict]:
    """Create MusicCRS predictions for one RRF configuration."""

    predictions = []

    for record in candidates:

        predicted_tracks = weighted_rrf(
            bm25_tracks=record["bm25_track_ids"],
            dense_tracks=record["dense_track_ids"],
            topk=topk,
            dense_weight=dense_weight,
            rrf_k=rrf_k,
        )

        predictions.append(
            {
                "session_id":
                    record["session_id"],

                "turn_number":
                    record["turn_number"],

                "predicted_track_ids":
                    predicted_tracks,

                "predicted_response":
                    "",
            }
        )

    return predictions


def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Tune weighted RRF for "
            "BM25 + dense retrieval"
        )
    )

    parser.add_argument(
        "--candidates",
        required=True,
        help=(
            "JSON file containing cached "
            "BM25 and dense candidate rankings"
        ),
    )

    parser.add_argument(
        "--ground_truth",
        required=True,
        help="Ground-truth JSON file",
    )

    parser.add_argument(
        "--catalog_size",
        type=int,
        default=47071,
        help="Total number of tracks",
    )

    parser.add_argument(
        "--topk",
        type=int,
        default=20,
        help="Number of final tracks",
    )

    parser.add_argument(
        "--rrf_k",
        type=int,
        default=60,
        help="RRF constant",
    )

    parser.add_argument(
        "--output",
        default="hybrid_tuning_results.json",
        help="Output JSON for tuning results",
    )

    args = parser.parse_args()

    # ---------------------------------------------------------
    # Header
    # ---------------------------------------------------------

    print()
    print("=" * 70)
    print("MusicCRS Hybrid Retrieval Tuning")
    print("=" * 70)

    print(
        f"Candidates   : {args.candidates}"
    )

    print(
        f"Ground truth : {args.ground_truth}"
    )

    print(
        f"Top-k        : {args.topk}"
    )

    print(
        f"RRF k        : {args.rrf_k}"
    )

    print(
        f"Catalog size : {args.catalog_size}"
    )

    # ---------------------------------------------------------
    # Load cached candidates
    # ---------------------------------------------------------

    print()
    print("Loading cached candidates...")

    with open(
        args.candidates,
        "r",
        encoding="utf-8",
    ) as f:
        candidates = json.load(f)

    print(
        f"Loaded {len(candidates)} "
        f"candidate records"
    )

    # ---------------------------------------------------------
    # Load ground truth
    # ---------------------------------------------------------

    print("Loading ground truth...")

    with open(
        args.ground_truth,
        "r",
        encoding="utf-8",
    ) as f:
        ground_truth = json.load(f)

    print(
        f"Loaded {len(ground_truth)} "
        f"ground-truth records"
    )

    # ---------------------------------------------------------
    # Sanity check
    # ---------------------------------------------------------

    candidate_keys = {
        (
            record["session_id"],
            record["turn_number"],
        )
        for record in candidates
    }

    ground_truth_keys = {
        (
            record["session_id"],
            record["turn_number"],
        )
        for record in ground_truth
    }

    missing_predictions = (
        ground_truth_keys
        - candidate_keys
    )

    if missing_predictions:

        raise ValueError(
            f"{len(missing_predictions)} "
            "ground-truth turns do not have "
            "cached candidate rankings."
        )

    print(
        "Candidate/ground-truth alignment: OK"
    )

    # ---------------------------------------------------------
    # Tune weights
    # ---------------------------------------------------------

    tuning_results = []

    print()
    print("=" * 70)
    print("Starting RRF weight tuning")
    print("=" * 70)

    for dense_weight in DENSE_WEIGHTS:

        print()
        print("-" * 60)

        print(
            f"Testing dense_weight = "
            f"{dense_weight:.2f}"
        )

        print("-" * 60)

        # -----------------------------------------------------
        # Generate predictions
        # -----------------------------------------------------

        predictions = build_predictions(
            candidates=candidates,
            dense_weight=dense_weight,
            topk=args.topk,
            rrf_k=args.rrf_k,
        )

        # -----------------------------------------------------
        # Evaluate
        #
        # evaluate() expects Python lists,
        # NOT file paths.
        # -----------------------------------------------------

        results = evaluate(
            predictions=predictions,
            ground_truth=ground_truth,
            catalog_size=args.catalog_size,
        )

        # -----------------------------------------------------
        # Store result
        # -----------------------------------------------------

        experiment = {
            "dense_weight":
                dense_weight,

            "bm25_weight":
                1.0,

            "rrf_k":
                args.rrf_k,

            "topk":
                args.topk,

            **results,
        }

        tuning_results.append(
            experiment
        )

        # -----------------------------------------------------
        # Display result
        # -----------------------------------------------------

        print(
            f"nDCG@1           : "
            f"{results['ndcg@1']:.6f}"
        )

        print(
            f"nDCG@10          : "
            f"{results['ndcg@10']:.6f}"
        )

        print(
            f"nDCG@20          : "
            f"{results['ndcg@20']:.6f}"
        )

        print(
            f"Catalog diversity: "
            f"{results['catalog_diversity']:.6f}"
        )

        print(
            f"Final score      : "
            f"{results['final_score']:.6f}"
        )

    # ---------------------------------------------------------
    # Sort by nDCG@20
    #
    # We use nDCG@20 for tuning on this small subset because
    # catalog diversity depends strongly on the number of
    # evaluated recommendation turns.
    # ---------------------------------------------------------

    tuning_results.sort(
        key=lambda result: result["ndcg@20"],
        reverse=True,
    )

    # ---------------------------------------------------------
    # Save results
    # ---------------------------------------------------------

    with open(
        args.output,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            tuning_results,
            f,
            indent=2,
        )

    # ---------------------------------------------------------
    # Print comparison table
    # ---------------------------------------------------------

    print()
    print("=" * 90)
    print("HYBRID TUNING RESULTS")
    print("=" * 90)

    header = (
        f"{'Dense':<10}"
        f"{'nDCG@1':<13}"
        f"{'nDCG@10':<13}"
        f"{'nDCG@20':<13}"
        f"{'Diversity':<13}"
        f"{'Final':<13}"
    )

    print(header)

    print("-" * 90)

    for result in tuning_results:

        print(
            f"{result['dense_weight']:<10.2f}"
            f"{result['ndcg@1']:<13.6f}"
            f"{result['ndcg@10']:<13.6f}"
            f"{result['ndcg@20']:<13.6f}"
            f"{result['catalog_diversity']:<13.6f}"
            f"{result['final_score']:<13.6f}"
        )

    # ---------------------------------------------------------
    # Best configuration
    # ---------------------------------------------------------

    best = tuning_results[0]

    print()
    print("=" * 70)
    print("BEST CONFIGURATION")
    print("=" * 70)

    print(
        f"BM25 weight       : "
        f"{best['bm25_weight']}"
    )

    print(
        f"Dense weight      : "
        f"{best['dense_weight']}"
    )

    print(
        f"RRF k             : "
        f"{best['rrf_k']}"
    )

    print(
        f"nDCG@1            : "
        f"{best['ndcg@1']:.6f}"
    )

    print(
        f"nDCG@10           : "
        f"{best['ndcg@10']:.6f}"
    )

    print(
        f"nDCG@20           : "
        f"{best['ndcg@20']:.6f}"
    )

    print(
        f"Catalog diversity : "
        f"{best['catalog_diversity']:.6f}"
    )

    print(
        f"Final score       : "
        f"{best['final_score']:.6f}"
    )

    print()
    print(
        f"Full tuning results saved to: "
        f"{args.output}"
    )


if __name__ == "__main__":
    main()
